# Generated by Django 4.2.1 on 2023-06-18 15:54

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_is_paid_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('PDF', 'PDF'), ('WEBPAGE', 'Webpage'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], default='TEXT', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_content', models.TextField(blank=True)),
                ('image_content', models.ImageField(blank=True, upload_to=course.models.PathAndRename('contents/'))),
                ('pdf_content', models.FileField(blank=True, upload_to=course.models.PathAndRename('contents/'))),
                ('webpage_content', models.URLField(blank=True)),
                ('audio_content', models.FileField(blank=True, upload_to=course.models.PathAndRename('contents/'))),
                ('audio_type', models.CharField(blank=True, max_length=100)),
                ('video_content', models.FileField(blank=True, upload_to=course.models.PathAndRename('contents/'))),
                ('video_type', models.CharField(blank=True, max_length=100)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
