# Generated by Django 4.2.1 on 2023-06-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
