# Generated by Django 4.2.1 on 2023-06-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
