# Generated by Django 4.2.1 on 2023-06-20 02:20

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_assignmentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='files',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='unique_id',
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=course.models.PathAndRename('submission/'))),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.assignmentsubmission')),
            ],
        ),
    ]
