# Generated by Django 4.2.1 on 2023-06-30 09:42

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_rename_progress_lessonprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='other_file_content',
            field=models.FileField(blank=True, upload_to=course.models.PathAndRename('contents/')),
        ),
    ]
