# Generated by Django 4.2.1 on 2023-06-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_content_other_file_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='other_file_content',
            new_name='other_content',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('PDF', 'PDF'), ('WEBPAGE', 'Webpage'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='TEXT', max_length=10),
        ),
    ]
