# Generated by Django 4.2.1 on 2023-07-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_quizattempt_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
    ]
