# Generated by Django 4.2.1 on 2023-07-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_quizattempt_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='choice',
        ),
    ]
