# Generated by Django 4.2.1 on 2023-07-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_quizattempt_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizprogress',
            unique_together=set(),
        ),
    ]
