# Generated by Django 4.2.1 on 2023-07-01 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_quizprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
