# Generated by Django 4.2.1 on 2023-07-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_assignment_attemptsallowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
