# Generated by Django 4.2.1 on 2023-07-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_assignment_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='grader',
        ),
        migrations.AddField(
            model_name='assignmentprogress',
            name='submission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.assignmentsubmission'),
            preserve_default=False,
        ),
    ]
