# Generated by Django 4.2.1 on 2023-07-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_remove_assignmentsubmission_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentprogress',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentprogress',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.assignmentsubmission'),
        ),
    ]
