# Generated by Django 4.2.1 on 2023-07-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_alter_assignmentprogress_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
