# Generated by Django 4.2.1 on 2023-07-25 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.CharField(default='7c2d88aa86a84c96ab0656fc4915cc70', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
