# Generated by Django 4.2.1 on 2023-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_certificate_created_on_alter_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.CharField(default='3d420ac73b324b0ba6578d7a39ad38a8', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
