# Generated by Django 4.2.1 on 2023-08-14 00:02

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_alter_certificate_id_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to=course.models.PathAndRename('thumbnails/')),
        ),
    ]
