# Generated by Django 4.2.1 on 2023-06-12 00:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_rename_product_orderitem_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='BillingAddress',
        ),
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Billing Address'},
        ),
    ]
