# Generated by Django 4.2.1 on 2023-06-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
