# Generated by Django 4.2.1 on 2023-07-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='full_name',
        ),
    ]
