# Generated by Django 4.2.1 on 2023-07-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
