# Generated by Django 4.2.1 on 2023-06-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_is_paid_course_price'),
        ('user', '0002_alter_usermodel_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
    ]
