# Generated by Django 4.2.1 on 2023-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('I', 'Instructor'), ('A', 'Admin')], default='S', max_length=2),
        ),
    ]
