# Generated by Django 4.2.1 on 2023-08-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
