# Generated by Django 4.2.1 on 2023-08-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.CharField(choices=[('email', 'Email'), ('announcement', 'Announcement'), ('grade', 'Grade'), ('chat', 'Chat')], default='E', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
